micronaut:
  application:
    name: propostasGrpc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/propostas
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'root'
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
